Running on euler with following parameters : 
User : atabin
Model : unet
Data folder : /cluster/work/igp_psr/ai4good/group-1b/data/
Saving directory : /cluster/scratch/atabin/unet/
Checkpoint path : /cluster/scratch/atabin/checkpoints/unet/
{'model': 'unet', 'data_dir': '/cluster/work/igp_psr/ai4good/group-1b/data/', 'checkpoint_path': '/cluster/scratch/atabin/checkpoints/unet/', 'save_dir': '/cluster/scratch/atabin/unet/'}
Running unet...
Traceback (most recent call last):
  File "/cluster/home/atabin/ClimateNet_AI4Good/run.py", line 33, in <module>
    train.run(
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/train.py", line 21, in run
    model = MODELS[model_name](config)
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/models/unet/unet.py", line 36, in __init__
    self.network = UNetModule(classes=len(self.config.labels), channels=len(list(self.config.fields))).cuda()
TypeError: __init__() missing 1 required positional argument: 'num_classes'
Done!
